spring:
  redis:
    host: 127.0.0.1
    port: 16379
    password: Zb123456
    database: 0
    timeout: 3000ms
    jedis:
      pool:
        max-wait: 200ms
        max-active: 8
        max-idle: 8
        min-idle: 0