spring:
  application:
    name: Demo1
  boot:
    admin:
      context-path: /admin
      client:
        url: http://localhost:${server.port}${spring.boot.admin.context-path}
        auto-registration: true
        enabled: true
        api-path: instances
        instance:
          health-url: http://localhost:${management.server.port}/actuator/health
          service-url: http://localhost:${server.port}/
          management-url: http://localhost:${management.server.port}/actuator
#          name: ${spring.application.name}
      monitor:
        status-interval: 3s
        status-lifetime: 3s
        default-timeout: 5000ms
      ui:
        theme:
          background-enabled: true
#          color: '#38bdf8'
#          # https://tailwindcss.com/docs/customizing-colors
#          palette:
#            50: '#38bdf8'   # 左侧菜单
#            100: '#c7d2fe'
#            200: '#a5b4fc'
#            300: '#818cf8'
#            400: '#6366f1'
#            500: '#4f46e5'
#            600: '#4338ca'
#            700: '#3730a3'
#            800: '#312e81'
#            900: '#1e1b4b'
        external-views:
          - label: "自定义TAB->百度"
            url: https://www.baidu.com
            order: 2000
#      notify:
#        mail:
#          to: zurkbob@gmail.com
#        pagerduty:
#          client:
#  mail:
#    port: 1025
#    host: mailhog-service.shoppingdemo

management:
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
  server:
    port: 10111
#    ssl:
#      enabled: false
#    base-path: /
  endpoints:
    web:
      exposure:
        include: '*'

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8080