spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zb123456
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1


mybatis:
#  check-config-location: true
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: io.github.hizhangbo.domain
  type-handlers-package: io.github.hizhangbo.typehandler
  # 下面两个二选一
#  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


logging:
  level:
    root: INFO
    io:
      github:
        hizhangbo:
          mapper: TRACE